#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "8f2774633e5344c3a3c146203ed14055"

[[d1_databases]]
binding = "DB"
database_name = "temp"
database_id = "0add5b4b-053a-406c-ae2a-a95d2f74ccb4"
preview_database_id = "0add5b4b-053a-406c-ae2a-a95d2f74ccb4"
migrations_dir = "app/drizzle"
